### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by lars18th** [itsuki-t/FakeDeviceData#1]
Hi,

Where I can download a binary release?

**Comment by itsuki-t** [comment]
I'm sorry, binary does not include because it depends on the model.
(e.g. OS version or manufacturer.)

I'll attach what I'm using, but it may not work properly with your phone.
[jp.rmitkt.xposed.fakedevicedata.zip](https://github.com/itsuki-t/FakeDeviceData/files/1385413/jp.rmitkt.xposed.fakedevicedata.zip)

**Comment by lars18th** [comment]
Hi,

Thank you! However, I'm using now another similar project with the same functionality:
https://github.com/bigsinger/AndroidIdChanger
It has now Nougat support.

Perhaps you like to collaborate with the developer of this other module.
